import type { GraphPlusSettings } from '../../graph+/types/settings/appSettings.ts';
import { DEFAULT_SETTINGS } from './defaultSettings.ts';

export type SettingsUpdateMode = 'live' | 'rebuild';

export type FieldContext = {
  settings: GraphPlusSettings;
  defaults: GraphPlusSettings;
};

type BaseField = {
  id: string;
  name: string;
  desc?: string;
  updateMode?: SettingsUpdateMode;
  visible?: (ctx: FieldContext) => boolean;
};

export type SliderField = BaseField & {
  kind: 'slider';
  min:    number;
  max:    number;
  step?:  number;
  get:        (settings: GraphPlusSettings)                 => number;
  getDefault: (defaults: GraphPlusSettings)                 => number;
  set:        (settings: GraphPlusSettings, value: number)  => void;
  clamp?:     (value: number)                               => number;
  toUi?:      (value: number, ctx: FieldContext)            => number;
  fromUi?:    (value: number, ctx: FieldContext)            => number;
};

export type ToggleField = BaseField & {
  kind: 'toggle';
  get:        (settings: GraphPlusSettings)                 => boolean;
  getDefault: (defaults: GraphPlusSettings)                 => boolean;
  set:        (settings: GraphPlusSettings, value: boolean) => void;
};

export type ColorField  = BaseField & {
  kind: 'color';
  get:        (settings: GraphPlusSettings)                             => string | undefined;
  getDefault: (defaults: GraphPlusSettings)                             => string | undefined;
  set:        (settings: GraphPlusSettings, value: string | undefined)  => void;
  fallback?: string;
};

export type TextField   = BaseField & {
  kind: 'text';
  placeholder?: string;
  get: (settings: GraphPlusSettings) => string;
  getDefault: (defaults: GraphPlusSettings) => string;
  set: (settings: GraphPlusSettings, value: string) => void;
  parse?: (value: string, ctx: FieldContext) => string;
};

export type FieldDescriptor =
  | SliderField
  | ToggleField
  | ColorField
  | TextField

export type SectionDescriptor = {
  id: string;
  title: string;
  fields: FieldDescriptor[];
};

const round = (value: number, decimals = 3): number => {
  const factor = Math.pow(10, decimals);
  return Math.round(value * factor) / factor;
};

export function getSettingsSchema(): SectionDescriptor[] {
  return [
    {
      id: 'base',
      title: 'Base',
      fields: [
        {
          id: 'min-node-radius',
          kind: 'slider',
          name: 'Minimum node radius',
          desc: 'Minimum radius for the smallest node in pixels.',
          updateMode: 'rebuild',
          min:  1,
          max: 20,
          step: 1,
          get: (s) => s.base.minNodeRadius,
          getDefault: (s) => s.base.minNodeRadius,
          set: (s, v) => { s.base.minNodeRadius = Math.round(v); },
          clamp: (v) => Math.max(1, Math.min(20, Math.round(v))),
        },
        {
          id: 'max-node-radius',
          kind: 'slider',
          name: 'Maximum node radius',
          desc: 'Maximum radius for the largest node in pixels.',
          updateMode: 'rebuild',
          min: 8,
          max: 80,
          step: 1,
          get: (s) => s.base.maxNodeRadius,
          getDefault: (s) => s.base.maxNodeRadius,
          set: (s, v) => { s.base.maxNodeRadius = Math.round(v); },
          clamp: (v) => Math.max(8, Math.min(80, Math.round(v))),
        },
        {
          id: 'label-font-size',
          kind: 'slider',
          name: 'Label font size',
          desc: 'Base label font size in pixels before zoom scaling.',
          updateMode: 'live',
          min: 6,
          max: 30,
          step: 1,
          get: (s) => s.base.labelFontSize,
          getDefault: (s) => s.base.labelFontSize,
          set: (s, v) => { s.base.labelFontSize = Math.round(v); },
          clamp: (v) => Math.max(6, Math.min(30, Math.round(v))),
        },
        {
          id: 'node-color',
          kind: 'color',
          name: 'Node color override',
          desc: 'Leave unset to use the active theme.',
          updateMode: 'live',
          get: (s) => s.base.nodeColor,
          getDefault: (s) => s.base.nodeColor,
          set: (s, v) => { s.base.nodeColor = v; },
        },
        {
          id: 'tag-color',
          kind: 'color',
          name: 'Tag color override',
          desc: 'Leave unset to use the active theme.',
          updateMode: 'live',
          get: (s) => s.base.tagColor,
          getDefault: (s) => s.base.tagColor,
          set: (s, v) => { s.base.tagColor = v; },
        },
        {
          id: 'link-color',
          kind: 'color',
          name: 'Link color override',
          desc: 'Leave unset to use the active theme.',
          updateMode: 'live',
          get: (s) => s.base.linkColor,
          getDefault: (s) => s.base.linkColor,
          set: (s, v) => { s.base.linkColor = v; },
        },
        {
          id: 'background-color',
          kind: 'color',
          name: 'Background color override',
          desc: 'Leave unset to use the active theme.',
          updateMode: 'live',
          get: (s) => s.base.backgroundColor,
          getDefault: (s) => s.base.backgroundColor,
          set: (s, v) => { s.base.backgroundColor = v; },
        },
        {
          id: 'label-color',
          kind: 'color',
          name: 'Label color override',
          desc: 'Leave unset to use the active theme.',
          updateMode: 'live',
          get: (s) => s.base.labelColor,
          getDefault: (s) => s.base.labelColor,
          set: (s, v) => { s.base.labelColor = v; },
        },
        {
          id: 'use-interface-font',
          kind: 'toggle',
          name: 'Use interface font',
          desc: 'Use the current Obsidian interface font for labels.',
          updateMode: 'live',
          get:        (s)     => Boolean(s.base.useInterfaceFont),
          getDefault: (s)     => Boolean(s.base.useInterfaceFont),
          set:        (s, v)  => { s.base.useInterfaceFont = v; },
        },
        {
          id: 'count-duplicate-links',
          kind: 'toggle',
          name: 'Count duplicate links',
          desc: 'Count multiple links between the same notes when computing degree.',
          updateMode: 'rebuild',
          get: (s)        => Boolean(s.base.countDuplicateLinks),
          getDefault: (s) => Boolean(s.base.countDuplicateLinks),
          set: (s, v)     => { s.base.countDuplicateLinks = v; },
        },
        {
          id: 'draw-double-lines',
          kind: 'toggle',
          name: 'Draw double lines',
          desc: 'Render mutual links as two parallel lines.',
          updateMode: 'live',
          get: (s) => Boolean(s.base.drawDoubleLines),
          getDefault: (s) => Boolean(s.base.drawDoubleLines),
          set: (s, v) => { s.base.drawDoubleLines = v; },
        },
        {
          id: 'show-tags',
          kind: 'toggle',
          name: 'Show tag nodes',
          desc: 'Show tag nodes and their links.',
          updateMode: 'rebuild',
          get: (s) => Boolean(s.base.showTags),
          getDefault: (s) => Boolean(s.base.showTags),
          set: (s, v) => { s.base.showTags = v; },
        },
        {
          id: 'show-labels',
          kind: 'toggle',
          name: 'Show labels',
          desc: 'Show file and tag labels.',
          updateMode: 'live',
          get: (s) => Boolean(s.base.showLabels),
          getDefault: (s) => Boolean(s.base.showLabels),
          set: (s, v) => { s.base.showLabels = v; },
        },
      ],
    },

    {
      id: 'layout',
      title: 'Layout',
      fields: [
        {
          id: 'link-length',
          kind: 'slider',
          name: 'Link length',
          desc: 'Preferred length in pixels for link springs.',
          updateMode: 'rebuild',
          min: 20,
          max: 400,
          step: 1,
          get: (s) => s.layout.linkLength,
          getDefault: (s) => s.layout.linkLength,
          set: (s, v) => { s.layout.linkLength = Math.round(v); },
          clamp: (v) => Math.max(20, Math.min(400, Math.round(v))),
        },
        {
          id: 'link-strength',
          kind: 'slider',
          name: 'Link strength',
          desc: 'UI 0–1 mapped to internal link stiffness.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.01,
          get: (s) => s.layout.linkStrength,
          getDefault: (s) => s.layout.linkStrength,
          set: (s, v) => { s.layout.linkStrength = v; },
          clamp: (v) => Math.max(0, Math.min(1, v)),
          toUi: (value) => Math.min(1, Math.max(0, value / 0.5)),
          fromUi: (value) => round(value * 0.5, 4),
        },
        {
          id: 'center-pull',
          kind: 'slider',
          name: 'Center pull',
          desc: 'UI 0–1 mapped to a small centering force.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.001,
          get: (s) => s.layout.centerPull,
          getDefault: (s) => s.layout.centerPull,
          set: (s, v) => { s.layout.centerPull = v; },
          clamp: (v) => Math.max(0, Math.min(1, v)),
          toUi: (value) => Math.min(1, Math.max(0, value / 0.01)),
          fromUi: (value) => round(value * 0.01, 5),
        },
        {
          id: 'note-plane-stiffness',
          kind: 'slider',
          name: 'Note plane stiffness',
          desc: 'How strongly notes are pulled toward the z=0 plane.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.01,
          get: (s) => s.layout.notePlaneStiffness,
          getDefault: (s) => s.layout.notePlaneStiffness,
          set: (s, v) => { s.layout.notePlaneStiffness = v; },
          clamp: (v) => Math.max(0, Math.min(1, v)),
          toUi: (value) => Math.min(1, Math.max(0, value / 0.02)),
          fromUi: (value) => round(value * 0.02, 5),
        },
        {
          id: 'tag-plane-stiffness',
          kind: 'slider',
          name: 'Tag plane stiffness',
          desc: 'How strongly tag nodes are pulled toward the x=0 plane.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.01,
          get: (s) => s.layout.tagPlaneStiffness,
          getDefault: (s) => s.layout.tagPlaneStiffness,
          set: (s, v) => { s.layout.tagPlaneStiffness = v; },
          clamp: (v) => Math.max(0, Math.min(1, v)),
          toUi: (value) => Math.min(1, Math.max(0, value / 0.02)),
          fromUi: (value) => round(value * 0.02, 5),
        },
        {
          id: 'world-center-x',
          kind: 'slider',
          name: 'World center X',
          desc: 'Target world center on the X axis.',
          updateMode: 'live',
          min: -2000,
          max: 2000,
          step: 10,
          get: (s) => s.layout.worldCenterX,
          getDefault: (s) => s.layout.worldCenterX,
          set: (s, v) => { s.layout.worldCenterX = Math.round(v); },
          clamp: (v) => Math.max(-2000, Math.min(2000, Math.round(v))),
        },
        {
          id: 'world-center-y',
          kind: 'slider',
          name: 'World center Y',
          desc: 'Target world center on the Y axis.',
          updateMode: 'live',
          min: -2000,
          max: 2000,
          step: 10,
          get: (s) => s.layout.worldCenterY,
          getDefault: (s) => s.layout.worldCenterY,
          set: (s, v) => { s.layout.worldCenterY = Math.round(v); },
          clamp: (v) => Math.max(-2000, Math.min(2000, Math.round(v))),
        },
        {
          id: 'world-center-z',
          kind: 'slider',
          name: 'World center Z',
          desc: 'Target world center on the Z axis.',
          updateMode: 'live',
          min: -2000,
          max: 2000,
          step: 10,
          get: (s) => s.layout.worldCenterZ,
          getDefault: (s) => s.layout.worldCenterZ,
          set: (s, v) => { s.layout.worldCenterZ = Math.round(v); },
          clamp: (v) => Math.max(-2000, Math.min(2000, Math.round(v))),
        },
      ],
    },

    {
      id: 'physics',
      title: 'Physics',
      fields: [
        {
          id: 'repulsion-strength',
          kind: 'slider',
          name: 'Repulsion strength',
          desc: 'UI 0–1 mapped internally. Higher values separate nodes more strongly.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.01,
          get: (s) => s.physics.repulsionStrength,
          getDefault: (s) => s.physics.repulsionStrength,
          set: (s, v) => { s.physics.repulsionStrength = v; },
          clamp: (v) => Math.max(0, Math.min(1, v)),
          toUi: (value) => {
            const ui = Math.sqrt(Math.max(0, value / 2000));
            return Math.min(1, Math.max(0, ui));
          },
          fromUi: (value) => round(value * value * 2000, 3),
        },
        {
          id: 'damping',
          kind: 'slider',
          name: 'Damping',
          desc: 'Velocity damping. Higher values reduce motion faster.',
          updateMode: 'live',
          min: 0.0,
          max: 1.0,
          step: 0.1,
          get: (s) => s.physics.damping,
          getDefault: (s) => s.physics.damping,
          set: (s, v) => { s.physics.damping = round(v, 3); },
          clamp: (v) => Math.max(0.0, Math.min(1.0, v)),
        },
        {
          id: 'mouse-gravity-enabled',
          kind: 'toggle',
          name: 'Mouse gravity',
          desc: 'Enable the mouse gravity well that attracts nearby nodes.',
          updateMode: 'live',
          get: (s) => Boolean(s.physics.mouseGravityEnabled),
          getDefault: (s) => Boolean(s.physics.mouseGravityEnabled),
          set: (s, v) => { s.physics.mouseGravityEnabled = v; },
        },
        {
          id: 'mouse-gravity-radius',
          kind: 'slider',
          name: 'Mouse gravity radius',
          desc: 'Scales the screen-space reach of the mouse gravity effect.',
          updateMode: 'live',
          min: 1,
          max: 50,
          step: 1,
          get: (s) => s.physics.mouseGravityRadius,
          getDefault: (s) => s.physics.mouseGravityRadius,
          set: (s, v) => { s.physics.mouseGravityRadius = Math.round(v); },
          clamp: (v) => Math.max(1, Math.min(50, Math.round(v))),
        },
        {
          id: 'mouse-gravity-strength',
          kind: 'slider',
          name: 'Mouse gravity strength',
          desc: 'Overall strength of the mouse gravity effect.',
          updateMode: 'live',
          min: 0,
          max: 50,
          step: 1,
          get: (s) => s.physics.mouseGravityStrength,
          getDefault: (s) => s.physics.mouseGravityStrength,
          set: (s, v) => { s.physics.mouseGravityStrength = Math.round(v); },
          clamp: (v) => Math.max(0, Math.min(50, Math.round(v))),
        },
        {
          id: 'mouse-gravity-exponent',
          kind: 'slider',
          name: 'Mouse gravity exponent',
          desc: 'Controls how quickly mouse gravity falls off with distance.',
          updateMode: 'live',
          min: 0.1,
          max: 6,
          step: 0.1,
          get: (s) => s.physics.mouseGravityExponent,
          getDefault: (s) => s.physics.mouseGravityExponent,
          set: (s, v) => { s.physics.mouseGravityExponent = round(v, 2); },
          clamp: (v) => Math.max(0.1, Math.min(6, v)),
        },
      ],
    },

    {
      id: 'camera',
      title: 'Camera',
      fields: [
        {
          id: 'momentum-scale',
          kind: 'slider',
          name: 'Momentum scale',
          desc: 'How much motion momentum is preserved during camera movement.',
          updateMode: 'live',
          min: 0,
          max: 1,
          step: 0.01,
          get: (s) => s.camera.momentumScale,
          getDefault: (s) => s.camera.momentumScale,
          set: (s, v) => { s.camera.momentumScale = round(v, 3); },
          clamp: (v) => Math.max(0, Math.min(1, v)),
        },
        {
          id: 'rotate-sensitivity-x',
          kind: 'slider',
          name: 'Rotate sensitivity X',
          desc: 'Horizontal orbit sensitivity.',
          updateMode: 'live',
          min: 0.001,
          max: 0.03,
          step: 0.001,
          get: (s) => s.camera.rotateSensitivityX,
          getDefault: (s) => s.camera.rotateSensitivityX,
          set: (s, v) => { s.camera.rotateSensitivityX = round(v, 4); },
          clamp: (v) => Math.max(0.001, Math.min(0.03, v)),
        },
        {
          id: 'rotate-sensitivity-y',
          kind: 'slider',
          name: 'Rotate sensitivity Y',
          desc: 'Vertical orbit sensitivity.',
          updateMode: 'live',
          min: 0.001,
          max: 0.03,
          step: 0.001,
          get: (s) => s.camera.rotateSensitivityY,
          getDefault: (s) => s.camera.rotateSensitivityY,
          set: (s, v) => { s.camera.rotateSensitivityY = round(v, 4); },
          clamp: (v) => Math.max(0.001, Math.min(0.03, v)),
        },
        {
          id: 'zoom-sensitivity',
          kind: 'slider',
          name: 'Zoom sensitivity',
          desc: 'Mouse wheel zoom sensitivity.',
          updateMode: 'live',
          min: 1,
          max: 100,
          step: 1,
          get: (s) => s.camera.zoomSensitivity,
          getDefault: (s) => s.camera.zoomSensitivity,
          set: (s, v) => { s.camera.zoomSensitivity = Math.round(v); },
          clamp: (v) => Math.max(1, Math.min(100, Math.round(v))),
        },
        {
          id: 'min-distance',
          kind: 'slider',
          name: 'Minimum distance',
          desc: 'Closest allowed camera distance from the target.',
          updateMode: 'live',
          min: 50,
          max: 5000,
          step: 10,
          get: (s) => s.camera.minDistance,
          getDefault: (s) => s.camera.minDistance,
          set: (s, v) => { s.camera.minDistance = Math.round(v); },
          clamp: (v) => Math.max(50, Math.min(5000, Math.round(v))),
        },
        {
          id: 'max-distance',
          kind: 'slider',
          name: 'Maximum distance',
          desc: 'Farthest allowed camera distance from the target.',
          updateMode: 'live',
          min: 100,
          max: 20000,
          step: 10,
          get: (s) => s.camera.maxDistance,
          getDefault: (s) => s.camera.maxDistance,
          set: (s, v) => { s.camera.maxDistance = Math.round(v); },
          clamp: (v) => Math.max(100, Math.min(20000, Math.round(v))),
        },
        {
          id: 'min-pitch',
          kind: 'slider',
          name: 'Minimum pitch',
          desc: 'Lowest allowed pitch angle in radians.',
          updateMode: 'live',
          min: -1.55,
          max: 0,
          step: 0.01,
          get: (s) => s.camera.minPitch,
          getDefault: (s) => s.camera.minPitch,
          set: (s, v) => { s.camera.minPitch = round(v, 3); },
          clamp: (v) => Math.max(-1.55, Math.min(0, v)),
        },
        {
          id: 'max-pitch',
          kind: 'slider',
          name: 'Maximum pitch',
          desc: 'Highest allowed pitch angle in radians.',
          updateMode: 'live',
          min: 0,
          max: 1.55,
          step: 0.01,
          get: (s) => s.camera.maxPitch,
          getDefault: (s) => s.camera.maxPitch,
          set: (s, v) => { s.camera.maxPitch = round(v, 3); },
          clamp: (v) => Math.max(0, Math.min(1.55, v)),
        },
        {
          id: 'initial-yaw',
          kind: 'slider',
          name: 'Initial yaw',
          desc: 'Default camera yaw in radians.',
          updateMode: 'rebuild',
          min: -Math.PI,
          max: Math.PI,
          step: 0.01,
          get: (s) => s.camera.initialState.yaw,
          getDefault: (s) => s.camera.initialState.yaw,
          set: (s, v) => { s.camera.initialState.yaw = round(v, 3); },
          clamp: (v) => Math.max(-Math.PI, Math.min(Math.PI, v)),
        },
        {
          id: 'initial-pitch',
          kind: 'slider',
          name: 'Initial pitch',
          desc: 'Default camera pitch in radians.',
          updateMode: 'rebuild',
          min: -1.55,
          max: 1.55,
          step: 0.01,
          get: (s) => s.camera.initialState.pitch,
          getDefault: (s) => s.camera.initialState.pitch,
          set: (s, v) => { s.camera.initialState.pitch = round(v, 3); },
          clamp: (v) => Math.max(-1.55, Math.min(1.55, v)),
        },
        {
          id: 'initial-distance',
          kind: 'slider',
          name: 'Initial distance',
          desc: 'Default camera distance from the target.',
          updateMode: 'rebuild',
          min: 100,
          max: 10000,
          step: 10,
          get: (s) => s.camera.initialState.distance,
          getDefault: (s) => s.camera.initialState.distance,
          set: (s, v) => { s.camera.initialState.distance = Math.round(v); },
          clamp: (v) => Math.max(100, Math.min(10000, Math.round(v))),
        },
        {
          id: 'initial-target-x',
          kind: 'slider',
          name: 'Initial target X',
          desc: 'Default camera target X position.',
          updateMode: 'rebuild',
          min: -5000,
          max: 5000,
          step: 10,
          get: (s) => s.camera.initialState.targetX,
          getDefault: (s) => s.camera.initialState.targetX,
          set: (s, v) => { s.camera.initialState.targetX = Math.round(v); },
          clamp: (v) => Math.max(-5000, Math.min(5000, Math.round(v))),
        },
        {
          id: 'initial-target-y',
          kind: 'slider',
          name: 'Initial target Y',
          desc: 'Default camera target Y position.',
          updateMode: 'rebuild',
          min: -5000,
          max: 5000,
          step: 10,
          get: (s) => s.camera.initialState.targetY,
          getDefault: (s) => s.camera.initialState.targetY,
          set: (s, v) => { s.camera.initialState.targetY = Math.round(v); },
          clamp: (v) => Math.max(-5000, Math.min(5000, Math.round(v))),
        },
        {
          id: 'initial-target-z',
          kind: 'slider',
          name: 'Initial target Z',
          desc: 'Default camera target Z position.',
          updateMode: 'rebuild',
          min: -5000,
          max: 5000,
          step: 10,
          get: (s) => s.camera.initialState.targetZ,
          getDefault: (s) => s.camera.initialState.targetZ,
          set: (s, v) => { s.camera.initialState.targetZ = Math.round(v); },
          clamp: (v) => Math.max(-5000, Math.min(5000, Math.round(v))),
        },
      ],
    },

    {
    id: 'tuning',
    title: 'Tuning',
    fields: [
        {
        id: 'link-thickness-scale',
        kind: 'slider',
        name: 'Link thickness scale',
        desc: 'Multiplies computed link thickness.',
        updateMode: 'rebuild',
        min: 0.1,
        max: 10,
        step: 0.1,
        get: (s) => s.tuning.linkThicknessScale,
        getDefault: (s) => s.tuning.linkThicknessScale,
        set: (s, v) => { s.tuning.linkThicknessScale = round(v, 2); },
        clamp: (v) => Math.max(0.1, Math.min(10, v)),
        },
        {
        id: 'link-thickness-min',
        kind: 'slider',
        name: 'Link thickness minimum',
        desc: 'Minimum rendered link thickness.',
        updateMode: 'rebuild',
        min: 0.1,
        max: 10,
        step: 0.1,
        get: (s) => s.tuning.linkThicknessMin,
        getDefault: (s) => s.tuning.linkThicknessMin,
        set: (s, v) => { s.tuning.linkThicknessMin = round(v, 2); },
        clamp: (v) => Math.max(0.1, Math.min(10, v)),
        },
        {
        id: 'node-degree-radius-scale',
        kind: 'slider',
        name: 'Node degree radius scale',
        desc: 'Controls how strongly node degree increases radius.',
        updateMode: 'rebuild',
        min: 0,
        max: 10,
        step: 0.1,
        get: (s) => s.tuning.nodeDegreeRadiusScale,
        getDefault: (s) => s.tuning.nodeDegreeRadiusScale,
        set: (s, v) => { s.tuning.nodeDegreeRadiusScale = round(v, 2); },
        clamp: (v) => Math.max(0, Math.min(10, v)),
        },
        {
        id: 'initial-jitter',
        kind: 'slider',
        name: 'Initial jitter',
        desc: 'Random position offset applied when seeding nodes.',
        updateMode: 'rebuild',
        min: 0,
        max: 500,
        step: 1,
        get: (s) => s.tuning.initialJitter,
        getDefault: (s) => s.tuning.initialJitter,
        set: (s, v) => { s.tuning.initialJitter = Math.round(v); },
        clamp: (v) => Math.max(0, Math.min(500, Math.round(v))),
        },
        {
        id: 'label-offset-y',
        kind: 'slider',
        name: 'Label offset Y',
        desc: 'Extra vertical label offset in screen pixels.',
        updateMode: 'live',
        min: -50,
        max: 100,
        step: 1,
        get: (s) => s.tuning.labelOffsetY,
        getDefault: (s) => s.tuning.labelOffsetY,
        set: (s, v) => { s.tuning.labelOffsetY = Math.round(v); },
        clamp: (v) => Math.max(-50, Math.min(100, Math.round(v))),
        },
        {
        id: 'pinch-threshold-px',
        kind: 'slider',
        name: 'Pinch threshold',
        desc: 'Minimum two-finger distance change before pinch starts.',
        updateMode: 'live',
        min: 0,
        max: 20,
        step: 0.1,
        get: (s) => s.tuning.pinchThresholdPx,
        getDefault: (s) => s.tuning.pinchThresholdPx,
        set: (s, v) => { s.tuning.pinchThresholdPx = round(v, 2); },
        clamp: (v) => Math.max(0, Math.min(20, v)),
        },
        {
        id: 'rotate-threshold-rad',
        kind: 'slider',
        name: 'Rotate threshold',
        desc: 'Minimum two-finger angle change before rotate starts.',
        updateMode: 'live',
        min: 0,
        max: 0.5,
        step: 0.001,
        get: (s) => s.tuning.rotateThresholdRad,
        getDefault: (s) => s.tuning.rotateThresholdRad,
        set: (s, v) => { s.tuning.rotateThresholdRad = round(v, 4); },
        clamp: (v) => Math.max(0, Math.min(0.5, v)),
        },
        {
        id: 'repulsion-min-distance',
        kind: 'slider',
        name: 'Repulsion min distance',
        desc: 'Minimum effective distance used by repulsion.',
        updateMode: 'live',
        min: 1,
        max: 200,
        step: 1,
        get: (s) => s.tuning.repulsionMinDistance,
        getDefault: (s) => s.tuning.repulsionMinDistance,
        set: (s, v) => { s.tuning.repulsionMinDistance = Math.round(v); },
        clamp: (v) => Math.max(1, Math.min(200, Math.round(v))),
        },
        {
        id: 'barnes-hut-theta',
        kind: 'slider',
        name: 'Barnes-Hut theta',
        desc: 'Lower is more accurate; higher is faster.',
        updateMode: 'live',
        min: 0.1,
        max: 2,
        step: 0.01,
        get: (s) => s.tuning.barnesHutTheta,
        getDefault: (s) => s.tuning.barnesHutTheta,
        set: (s, v) => { s.tuning.barnesHutTheta = round(v, 3); },
        clamp: (v) => Math.max(0.1, Math.min(2, v)),
        },
        {
        id: 'barnes-hut-epsilon',
        kind: 'slider',
        name: 'Barnes-Hut epsilon',
        desc: 'Softening factor to avoid singularities.',
        updateMode: 'live',
        min: 0.000001,
        max: 0.1,
        step: 0.000001,
        get: (s) => s.tuning.barnesHutEpsilon,
        getDefault: (s) => s.tuning.barnesHutEpsilon,
        set: (s, v) => { s.tuning.barnesHutEpsilon = v; },
        clamp: (v) => Math.max(0.000001, Math.min(0.1, v)),
        },
        {
        id: 'mouse-gravity-padding-world',
        kind: 'slider',
        name: 'Mouse gravity padding',
        desc: 'Extra world-space padding near the mouse gravity field.',
        updateMode: 'live',
        min: 0,
        max: 100,
        step: 1,
        get: (s) => s.tuning.mouseGravityPaddingWorld,
        getDefault: (s) => s.tuning.mouseGravityPaddingWorld,
        set: (s, v) => { s.tuning.mouseGravityPaddingWorld = Math.round(v); },
        clamp: (v) => Math.max(0, Math.min(100, Math.round(v))),
        },
    ],
    },
    
    {
      id: 'ui',
      title: 'UI',
      fields: [
        {
          id: 'long-press-ms',
          kind: 'slider',
          name: 'Long press duration',
          desc: 'Milliseconds before a pointer press counts as a long press.',
          updateMode: 'live',
          min: 100,
          max: 1500,
          step: 10,
          get: (s) => s.ui.longPressMs,
          getDefault: (s) => s.ui.longPressMs,
          set: (s, v) => { s.ui.longPressMs = Math.round(v); },
          clamp: (v) => Math.max(100, Math.min(1500, Math.round(v))),
        },
        {
          id: 'drag-threshold-px',
          kind: 'slider',
          name: 'Drag threshold',
          desc: 'Pointer movement in pixels before a drag begins.',
          updateMode: 'live',
          min: 0,
          max: 40,
          step: 1,
          get: (s) => s.ui.dragThresholdPx,
          getDefault: (s) => s.ui.dragThresholdPx,
          set: (s, v) => { s.ui.dragThresholdPx = Math.round(v); },
          clamp: (v) => Math.max(0, Math.min(40, Math.round(v))),
        },
        {
          id: 'double-click-ms',
          kind: 'slider',
          name: 'Double click duration',
          desc: 'Milliseconds allowed between clicks for a double click.',
          updateMode: 'live',
          min: 100,
          max: 1000,
          step: 10,
          get: (s) => s.ui.doubleClickMs,
          getDefault: (s) => s.ui.doubleClickMs,
          set: (s, v) => { s.ui.doubleClickMs = Math.round(v); },
          clamp: (v) => Math.max(100, Math.min(1000, Math.round(v))),
        },
      ],
    },
  ];
}

export function getSettingsFieldContext(settings: GraphPlusSettings): FieldContext {
  return {
    settings,
    defaults: DEFAULT_SETTINGS,
  };
}