import './contracts/architecture.test.ts';
import './contracts/client-artifact.test.ts';
import './contracts/document.test.ts';
import './core/document-store.test.ts';
import './core/filter.test.ts';
import './core/profile.test.ts';
import './core/view-state.test.ts';
import './runtime/interaction.test.ts';
import './runtime/modules.test.ts';
import './runtime/session.test.ts';
import './service/service.test.ts';
import './service/actions.test.ts';
import './service/neutral-sample.test.ts';
import './obsidian/persistence.test.ts';
import './obsidian/settings-controller.test.ts';
import './obsidian/ui-policy.test.ts';
import './graph-plus/adapter.test.ts';
import { runTests } from './support/harness.ts';

void runTests();
